name: Main Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency:
      group: cd-build
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 22.x
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.1"
          bundler-cache: true

      - run: pnpm install --frozen-lockfile

      - run: pnpm run css:build
      - run: bundle exec jekyll build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: cd-deploy
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
